### PR TITLE
Upgrade pagerfanta

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by mbabker** [comment]
Like @pamil mentioned in https://github.com/Sylius/Sylius/issues/10928#issuecomment-611584818 there's probably going to need to be a B/C layer to account for the changes in my initial 2.0 release.

Note, this is only going to cover the B/C breaks I made between the last White October release and my initial release.  Everything else found in the bundle now, or the main Pagerfanta library itself, I am handling with appropriate care.

Renamed Classes:

| Old Class Name                                                                             | New Class Name                                                                       |
| ------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------ |
| `WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle`                               | `BabDev\PagerfantaBundle\BabDevPagerfantaBundle`                                     |
| `WhiteOctober\PagerfantaBundle\DependencyInjection\Configuration`                          | `BabDev\PagerfantaBundle\DependencyInjection\Configuration`                          |
| `WhiteOctober\PagerfantaBundle\DependencyInjection\WhiteOctoberPagerfantaExtension`        | `BabDev\PagerfantaBundle\DependencyInjection\BabDevPagerfantaExtension`              |
| `WhiteOctober\PagerfantaBundle\DependencyInjection\Compiler\AddPagerfantasPass`            | `BabDev\PagerfantaBundle\DependencyInjection\CompilerPass\AddPagerfantasPass`        |
| `WhiteOctober\PagerfantaBundle\EventListener\ConvertNotValidCurrentPageToNotFoundListener` | `BabDev\PagerfantaBundle\EventListener\ConvertNotValidCurrentPageToNotFoundListener` |
| `WhiteOctober\PagerfantaBundle\EventListener\ConvertNotValidMaxPerPageToNotFoundListener`  | `BabDev\PagerfantaBundle\EventListener\ConvertNotValidMaxPerPageToNotFoundListener`  |
| `WhiteOctober\PagerfantaBundle\Twig\PagerfantaExtension`                                   | `BabDev\PagerfantaBundle\Twig\PagerfantaExtension`                                   |
| `WhiteOctober\PagerfantaBundle\View\DefaultTranslatedView`                                 | `BabDev\PagerfantaBundle\View\DefaultTranslatedView`                                 |
| `WhiteOctober\PagerfantaBundle\View\SemanticUiTranslatedView`                              | `BabDev\PagerfantaBundle\View\SemanticUiTranslatedView`                              |
| `WhiteOctober\PagerfantaBundle\View\TranslatedView`                                        | `BabDev\PagerfantaBundle\View\TranslatedView`                                        |
| `WhiteOctober\PagerfantaBundle\View\TwitterBootstrap3TranslatedView`                       | `BabDev\PagerfantaBundle\View\TwitterBootstrap3TranslatedView`                       |
| `WhiteOctober\PagerfantaBundle\View\TwitterBootstrap4TranslatedView`                       | `BabDev\PagerfantaBundle\View\TwitterBootstrap4TranslatedView`                       |
| `WhiteOctober\PagerfantaBundle\View\TwitterBootstrapTranslatedView`                        | `BabDev\PagerfantaBundle\View\TwitterBootstrapTranslatedView`                        |

There are also these changes from the upgrade guide that Sylius would need to either account for or just document as B/C breaks:

> Made all classes final except for the Pagerfanta views

If someone subclassed anything in the `DependencyInjection` namespace, the event listeners, or the Twig extension, then the final keyword is a hard B/C break for them.  Realistically these classes shouldn't be considered extension points but considering they were never annotated internal or final and did not use the final keyword before I took on the package then it's possible someone subclassed here.

> The bundle's root configuration node has moved from white_october_pagerfanta to babdev_pagerfanta, you will need to update the configuration in your application

This one's because of the PHP class rename to match Symfony's expectations, the bundle doesn't parse the WhiteOctober namespace configs.

> Removed the `white_october_pagerfanta.view_factory.class` parameter, use a compiler pass if you wish to change this class

For this one, a compiler pass could be added (which IMO should be marked immediately deprecated) to check if the parameter is defined in the container, and if so change the class for the `pagerfanta.view_factory` service to the one specified in that parameter.

> Renamed the `white_october_pagerfanta.view_factory` service to `pagerfanta.view_factory` to be consistent with other service IDs and made the service public

> Renamed the `twig.extension.pagerfanta` service to `pagerfanta.twig_extension`

Service aliases (which IMO should be marked immediately deprecated) could be added for these two changes.

**Comment by loic425** [comment]
@mbabker Thank you for this awesome detailed comment 👍

**Comment by loic425** [comment]
@mbabker I have a pagerfanta view I wrote for Foundation but not submitted yet... I think I will make a pull request on your bundle to have a better idea of the changes.

**Comment by loic425** [comment]
Replaced by https://github.com/Sylius/SyliusResourceBundle/pull/175

**Pull request closed without merging**
