### PR TITLE
Change all MasterRequest calls to MainRequest

### PR DESCRIPTION
**Pull request by Roshyo**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Review by lchrusciel — APPROVED** [review]
Is their a way to test this behaviour?

**Comment by Roshyo** [comment]
I think that running pipe through Symfony 6 should be enough as it is removed there

**Comment by loic425** [comment]
> I think that running pipe through Symfony 6 should be enough as it is removed there

I agree with you

**Review by loic425 — APPROVED** [review]

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
Thanks, Stephane! :tada:

**Pull request merged**
