### PR TITLE
Allow downgrading pagerfanta to version 2.*

### PR DESCRIPTION
**Pull request by gseidel**
| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #415 
| License         | MIT

Allow user downgrading to pagerfanta version `2.*`

### CODE REVIEW

**Review by lchrusciel — COMMENTED** [review]
Hey Gerhard,

once again thanks for the contribution. Could you give a try to adjust our CI pipeline to test Resource with both pagerfantas?

**Comment by loic425** [comment]
Does it makes sense now? Pagerfanta is on 4.x now.

**Comment by gseidel** [comment]
@loic425 Oh I never provide a test for that. But this is also not so easy, we need a CI that test also the lowest version. For me that PR could be closed. I guess that PR concern only a few people at the past and is outdated now.

**Comment by loic425** [comment]
Ok so I'm closing it. Thx a lot

**Pull request closed without merging**
