### PR TITLE
Upgrade to WinzouStateMachineBundle ^0.4.1

### PR DESCRIPTION
**Pull request by ahilke**
winzou/state-machine-bundle 0.4.1 fixes an incompatibility with Symfony 4. Allowing users to upgrade the state-machine-bundle make using Symfony 4 easier.

### CODE REVIEW

**Comment by mamazu** [comment]
:+1: Although this might be a BC break.

**Comment by pamil** [comment]
We'd need to add a compiler pass which provides BC with 0.3 behaviour (`sm.factory` service etc.)

**Comment by mamazu** [comment]
Or probably an alias will just do.

**Comment by pamil** [comment]
An alias in a compiler pass, since we'd modify services coming from outside resource bundle.

**Pull request closed without merging**
