### PR TITLE
Add support for Symfony 6

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by loic425** [comment]
@lchrusciel It's blocked by https://github.com/Sylius/SyliusResourceBundle/pull/298

**Comment by Zales0123** [comment]
@loic425 rebase needed, it would be wonderful to have it merge soon :)

**Comment by loic425** [comment]
We need [this PR](https://github.com/Sylius/SyliusResourceBundle/issues/337) to be merged before

**Comment by Zales0123** [comment]
Waiting for https://github.com/winzou/StateMachineBundle/pull/64

**Comment by MrSrsen** [comment]
Hello. Issue https://github.com/winzou/StateMachineBundle/pull/64 was resolved and I was wondering when this issue could move forward.

Is there anything that I could do to help Symfony 6 support? I would like to use SyliusResourceBundle in my project but I am waiting for this issue to be resolved.

**Comment by loic425** [comment]
> Hello. Issue [winzou/StateMachineBundle#64](https://github.com/winzou/StateMachineBundle/pull/64) was resolved and I was wondering when this issue could move forward.
> 
> Is there anything that I could do to help Symfony 6 support? I would like to use SyliusResourceBundle in my project but I am waiting for this issue to be resolved because I want to use Symfony 6.

Our main blocker for Sylius package is the phpspec usage. We plan to fork this package. Symfony 6 support is the next step after releasing the next stable release of this bundle.

**Comment by loic425** [comment]
Closed in favour of https://github.com/Sylius/SyliusResourceBundle/pull/396

**Pull request closed without merging**
