### PR TITLE
Flip back service ids and FQCN

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

Replace #549 

Fix the BC-break from #498

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by loic425** [comment]
@mbabker During internal discussions, we suggest to duplicate the services (both with IDs and FQCN) and adding deprecations to the IDs ones. WDYT?

**Comment by loic425** [comment]
@mbabker Exactly what I did here for only 2 services for now #549

**Comment by mbabker** [comment]
I think that'd be a little overkill.  At that point, you have two independent services and an asinine number of logged container deprecations that you can't do anything about.

The closest that Symfony suggests to a naming convention for service IDs in bundles in the [best practices](https://symfony.com/doc/current/bundles/best_practices.html#services) is prefixing service IDs.  That to me implies that it's better for bundles to not use FQCN's as service IDs, and to purposefully create aliases for the FQCN of interfaces that a service defines where it's feasible.

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Loïc! :1st_place_medal:

**Pull request merged**
