### PR TITLE
Use ConfigurableViewHandlerInterface in ViewHandler

### PR DESCRIPTION
**Pull request by kayue**
This change to allow developer provide their own version of `FOS\RestBundle\View\ViewHandler`

### CODE REVIEW

**Comment by mamazu** [comment]
@kayue Could you fix the tests please? Because I am having the same issue.

**Comment by lchrusciel** [comment]
Hey, @kayue! I've tried to update your codebase and improve cs and I've rebased to the newest master as well. There are some issues with autowiring right now, and I'm may not be able to take over this PR further.

**Comment by mamazu** [comment]
I have rebased the branch on the current master and it works. This would be really nice to get in.

**Comment by mamazu** [comment]
Any update on this issue?

**Comment by loic425** [comment]
@mamazu Travis build is red with autowiring.

**Comment by kayue** [comment]
Closed by https://github.com/Sylius/SyliusResourceBundle/pull/150

**Pull request closed without merging**
