### PR TITLE
Resource alias, always return 2 array items

### LINKED ISSUE #473: Resource naming with more than 2 dots
**Sylius version affected**: 1.11

**Description**  

Using an alias with more than one dot.

`\Sylius\Component\Resource\Metadata\Metadata::parseAlias` will return an array with more than 2 elements and only the first two items of this array will be used as `$applicationName` and `$name`.
Then the metadata will search for the wrong entity reference leading to a wrong schema generation.

**Steps to reproduce**

```yaml
sylius_resource:
    resources:
        app.quiz.question: # using 2 dots
            driver: doctrine/orm
            classes:
                model: App\Entity\Quiz\Question
                interface: App\Entity\QuestionInterface
            translation:
                classes:
                    model: App\Entity\Quiz\QuestionTranslation
                    interface: App\Entity\QuestionTranslationInterface
```

Will generate this diff :

```sql
CREATE TABLE app_response (id INT AUTO_INCREMENT NOT NULL, question_id INT NOT NULL, quiz_id INT DEFAULT NULL, INDEX IDX_A79809F81E27F6BF (question_id), INDEX IDX_A79809F8853CD175 (quiz_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE app_response_translation (id INT AUTO_INCREMENT NOT NULL, response VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE app_question_translation ADD CONSTRAINT FK_C27CB3C42C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES app_question_translation (id) ON DELETE CASCADE;
```

We can see on the last SQL query a self referenced foreign key instead of a reference to the `app_response`.

**Possible Solution**  

Replace the return of `\Sylius\Component\Resource\Metadata\Metadata::parseAlias` by :

```php
return explode('.', $alias, 2);
```
to always return 2 array items.

### PR DESCRIPTION
**Pull request by Prometee**
| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #473 
| License         | MIT

This PR fix #473

### CODE REVIEW

**Review by lchrusciel — APPROVED** [review]
We should fix the build first

**Comment by Prometee** [comment]
@lchrusciel build errors are fixed now 😉

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "more-than-2-dots"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
I've moved your fix to 1.9, to have it available earlier, but can you add one more spec case here: https://github.com/Sylius/SyliusResourceBundle/blob/1.9/src/Component/spec/Metadata/MetadataSpec.php, to avoid regression in future?

**Review by Roshyo — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Francis! :tada:

**Comment by Prometee** [comment]
> I've moved your fix to 1.9, to have it available earlier, but can you add one more spec case here: https://github.com/Sylius/SyliusResourceBundle/blob/1.9/src/Component/spec/Metadata/MetadataSpec.php, to avoid regression in future?

@lchrusciel sure I will open an other PR based on 1.9 this time 😉

**Comment by Prometee** [comment]
@lchrusciel arf you were faster than me 😆

**Pull request merged**
