### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by loic425**
Fixes https://github.com/Sylius/SyliusResourceBundle/issues/121

Pull request to track where we are on Symfony 5 support.
https://github.com/Sylius/SyliusResourceBundle/pull/124 Replace deprecated object manager
https://github.com/Sylius/SyliusResourceBundle/pull/125 Replace deprecated object repository
https://github.com/Sylius/SyliusResourceBundle/pull/126 Replace dbal types
https://github.com/Sylius/SyliusResourceBundle/pull/135 Allow for DoctrineBundle ^2.0

### CODE REVIEW

**Comment by pamil** [comment]
Rebased with master :)

**Comment by pamil** [comment]
Seems like `SYMFONY_VERSION` is not having any effect so that's why the build is passing :/

**Comment by loic425** [comment]
@pamil this build is green!!

**Comment by loic425** [comment]
@pamil Yes we need to update symfony dependencies on composer.json with SYMFONY_VERSION on travis. Something like that https://github.com/Sylius/Sylius/blob/master/bin/require-symfony-version.
I think it could be possible with a simple "sed" command.

**Comment by loic425** [comment]
@pamil https://regexr.com/4rhjj

**Comment by loic425** [comment]
Replaced by #187

**Pull request closed without merging**
