### PR TITLE
Critiera Applier

### PR DESCRIPTION
**Pull request by mamazu**
In the current version of the plugin if you are using it to generate CRUD routes for an api the filter mechanism doesn't support filtering with only a part of the search term.

In this commit I am trying to fix this.

### CODE REVIEW

**Comment by mamazu** [comment]
In this pull request I just noticed that I could change the logic without a test noticing which is usually a bad sign. But I noticed that the tests only test the status code not the content. Which makes tests that should fail like the one `BookApiTest:it_applies_sorting_for_existing_field` pass because the response code is 200 but the body is empty.

**Comment by lchrusciel** [comment]
Filtration is handled with grid bundle, and the empty result is returned due to lack of grid configuration. From what I see, we have already coupled grid and resource bundle (another question is, do we want it that way), so we should probably add a grid definition for books, so it will be possible to filtrate them or remove obsolete tests. 

Anyway, did you encounter any issue related to this functionality?

**Comment by mamazu** [comment]
These are two different things in my opinion. I am talking about the CRUD Api that is generated with the bundle. This has nothing to do with grids.

**Comment by lchrusciel** [comment]
Not sure, if I will find time to solve this issue, but I truly believe, that adding a grid to this route would solve the problem

**Comment by mamazu** [comment]
Yes, that would also be an idea. I was also surprised about the fact that the grid filter work different than the API filters.

**Pull request closed without merging**
