### PR TITLE
Fix type of serialization groups

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | 
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Review by Roshyo — APPROVED** [review]

**Review by vvasiloi — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]
Can we write super simple case for that to avoid issues in the future?

**Comment by loic425** [comment]
> Can we write super simple case for that to avoid issues in the future?

There's already a simple test.... But I don't even know how it keeps working with the wrong type.
https://github.com/Sylius/SyliusResourceBundle/blob/master/src/Bundle/Tests/Routing/RoutesAttributesLoaderTest.php#L147

**Comment by lchrusciel** [comment]
thats the worst type of bugs - you know, that tests should fail, but they are green :(

**Comment by loic425** [comment]
> thats the worst type of bugs - you know, that tests should fail, but they are green :(

Yes but the result is ok, even with the wrong type, I also test it manually 🗡️

**Comment by loic425** [comment]
@lchrusciel I think there is some "magic" somewhere :)

**Comment by vvasiloi** [comment]
It works... must be a bug (or feature) of PHP: https://3v4l.org/fOejp#v8.0.15

<details>
<summary>Screenshot</summary>
image
</details>

**Comment by vvasiloi** [comment]
And although I only defined the `serializationGroups` in the attribute class, I also passed (unintentionally, copy/paste) name, path and controller and all were returned as a result.

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, Loïc! :1st_place_medal:

**Pull request merged**
